### ISSUE TITLE
Config file?

### ISSUE THREAD

**Issue by sricc** [petejkim/factory-lady#4]
Is there a way to create a single file or folder with the factories in them the way actory_girl  allows?

Would be cool to be able to place a folder with multiple files or single file (maybe JSON format (factories.js?) with all the factories.  

Something like: 

test/
  factories.js

or

test/
  factories/
     person.js
     jobs.js
     ....

Thoughts?

**Comment by petejkim** [comment]
yep you can create your factories anywhere and have them `require`ed... are you using it with nodejs?

**Comment by sricc** [comment]
Yes, I am using nodejs..  I understand that you can put them anywhere and require them, just thought it would be nice to not have to require them at all and that factory-lady would have a default place to look for the files.  Just wanted to get your thoughts on it, I could put something together and submit a pull request if you feel it's a worthwhile feature.  If not, no worries,  thanks for your response!
